### ISSUE TITLE
undefined method `first' for nil:NilClass bug

### ISSUE THREAD

**Issue by wchen-r7** [taf2/speech2text#10]
I was trying out speech2text and then I hit this problem :-(

backtrace:

```
/Users/lab/.rvm/gems/ruby-1.9.2-p180/gems/speech2text-0.3.6/lib/speech/audio_inspector.rb:55:in `initialize': undefined method `first' for nil:NilClass (NoMethodError)
    from /Users/lab/.rvm/gems/ruby-1.9.2-p180/gems/speech2text-0.3.6/lib/speech/audio_splitter.rb:76:in `new'
    from /Users/lab/.rvm/gems/ruby-1.9.2-p180/gems/speech2text-0.3.6/lib/speech/audio_splitter.rb:76:in `initialize'
    from /Users/lab/.rvm/gems/ruby-1.9.2-p180/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:30:in `new'
    from /Users/lab/.rvm/gems/ruby-1.9.2-p180/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:30:in `to_json'
    from /Users/lab/.rvm/gems/ruby-1.9.2-p180/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:20:in `to_text'
    from /Users/lab/.rvm/gems/ruby-1.9.2-p180/gems/speech2text-0.3.6/bin/speech2text:11:in `<top (required)>'
    from /Users/lab/.rvm/gems/ruby-1.9.2-p180/bin/speech2text:19:in `load'
    from /Users/lab/.rvm/gems/ruby-1.9.2-p180/bin/speech2text:19:in `<main>'
```

**Comment by tboyko** [comment]
Seeing the same issue here.

**Comment by tboyko** [comment]
Issue occurs when the `ffmpeg` package, which is required, is not installed on the local machine. Suggestion to explicitly state need to install this package in `README.md`.
