### ISSUE TITLE
 `convert_chunk': undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by hoblin** [taf2/speech2text#14]
``` bash
hoblin@ubuntu:~/src/stt$ ffmpeg -version
ffmpeg version 0.8.5-4:0.8.5-0ubuntu0.12.04.1, Copyright (c) 2000-2012 the Libav developers
  built on Jan 24 2013 18:03:14 with gcc 4.6.3
*** THIS PROGRAM IS DEPRECATED ***
This program is only provided for compatibility and will be removed in a future release. Please use avconv instead.
ffmpeg 0.8.5-4:0.8.5-0ubuntu0.12.04.1
libavutil    51. 22. 1 / 51. 22. 1
libavcodec   53. 35. 0 / 53. 35. 0
libavformat  53. 21. 1 / 53. 21. 1
libavdevice  53.  2. 0 / 53.  2. 0
libavfilter   2. 15. 0 /  2. 15. 0
libswscale    2.  1. 0 /  2.  1. 0
libpostproc  52.  0. 0 / 52.  0. 0
hoblin@ubuntu:~/src/stt$ flac -v
flac 1.2.1
hoblin@ubuntu:~/src/stt$ ruby -v
ruby 2.0.0p57 (2013-03-12 revision 39784) [i686-linux]
hoblin@ubuntu:~/src/stt$ gem list speech2text

*** LOCAL GEMS ***

speech2text (0.3.6)
hoblin@ubuntu:~/src/stt$ speech2text test.wav 

/usr/local/lib/ruby/gems/2.0.0/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:69:in `convert_chunk': undefined method `[]' for nil:NilClass (NoMethodError)
    from /usr/local/lib/ruby/gems/2.0.0/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:34:in `block in to_json'
    from /usr/local/lib/ruby/gems/2.0.0/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:32:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:32:in `to_json'
    from /usr/local/lib/ruby/gems/2.0.0/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:20:in `to_text'
    from /usr/local/lib/ruby/gems/2.0.0/gems/speech2text-0.3.6/bin/speech2text:11:in `<top (required)>'
    from /usr/local/bin/speech2text:23:in `load'
    from /usr/local/bin/speech2text:23:in `<main>'
```

**Comment by vmeng** [comment]
:+1: 
I also have this problem. This is because i use an empty or only noisy audio file to post to google. And google return {"status":5,"id":"d67b8bcf33e6d87ccce91839671bad2c-1","hypotheses":[]}

My error log is :
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/viki/Documents/Project/vendor/ruby/1.9.1/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:78:in`convert_chunk'
    /Users/viki/Documents/Project/vendor/ruby/1.9.1/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:40:in `block in to_json'
    /Users/viki/Documents/Project/vendor/ruby/1.9.1/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:36:in`each'
    /Users/viki/Documents/Project/vendor/ruby/1.9.1/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:36:in `to_json'
    /Users/viki/Documents/Project/vendor/ruby/1.9.1/gems/speech2text-0.3.6/lib/speech/audio_to_text.rb:21:in`to_text'

I puts some log, the line num may not correct.

Is any body can fix it ?

**Comment by bartolsthoorn** [comment]
Checked the source code because I also ran in this error just today. It only happens when Google was unable to convert the audio to text. You should check your audio input and try again with a different file. Make sure it's loud and clear and in wav format. Also try to run the sample wav files from the repository.
