### ISSUE TITLE
NoMethodError: undefined method `first' for nil:NilClass

### ISSUE THREAD

**Issue by viniciusmo** [taf2/speech2text#15]
My code

 audio = Speech::AudioToText.new("tmp/sounds/teste.wav")
 p audio.to_json

And the tests are failure

4 tests, 0 assertions, 0 failures, 3 errors

**Comment by viniciusmo** [comment]
1) Error:
test_audio_splitter(SpeechAudioSplitterTest):
NoMethodError: undefined method `first' for nil:NilClass
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_inspector.rb:55:in`initialize'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_splitter.rb:76:in `new'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_splitter.rb:76:in`initialize'
    /Users/viniciusmo/Open Source/speech2text/test/audio_splitter_test.rb:9:in `new'
    /Users/viniciusmo/Open Source/speech2text/test/audio_splitter_test.rb:9:in`test_audio_splitter'

  2) Error:
test_audio_to_text(SpeechAudioToTextTest):
NoMethodError: undefined method `first' for nil:NilClass
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_inspector.rb:55:in`initialize'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_splitter.rb:76:in `new'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_splitter.rb:76:in`initialize'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_to_text.rb:31:in `new'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_to_text.rb:31:in`to_json'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_to_text.rb:20:in `to_text'
    /Users/viniciusmo/Open Source/speech2text/test/audio_to_text_test.rb:13:in`test_audio_to_text'

  3) Error:
test_longer_audio(SpeechAudioToTextTest):
NoMethodError: undefined method `first' for nil:NilClass
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_inspector.rb:55:in`initialize'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_splitter.rb:76:in `new'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_splitter.rb:76:in`initialize'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_to_text.rb:31:in `new'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_to_text.rb:31:in`to_json'
    /Users/viniciusmo/Open Source/speech2text/lib/speech/audio_to_text.rb:20:in `to_text'
    /Users/viniciusmo/Open Source/speech2text/test/audio_to_text_test.rb:18:in`test_longer_audio'

4 tests, 0 assertions, 0 failures, 3 errors
