### ISSUE TITLE
Error during conversion

### ISSUE THREAD

**Issue by benhei** [taf2/speech2text#4]
If I execute

> ruby speech2text part.wav

i get the following output:

Chunk count: 1
convert: ./chunk-part-0.wav to flac
C:/Ruby192/lib/ruby/gems/1.9.1/gems/speech2text-0.3.5/lib/speech/audio_splitter.rb:59:in `to_flac': failed to convert chunk: ./chunk-part-0.wav with flac ./chunk-part-0.wav (RuntimeError)
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/speech2text-0.3.5/lib/speech/audio_to_text.rb:18:in`block in to_text'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/speech2text-0.3.5/lib/speech/audio_to_text.rb:17:in `each'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/speech2text-0.3.5/lib/speech/audio_to_text.rb:17:in`to_text'
        from speech2text:11:in `<main>'

Any ideas about the reason?

**Comment by taf2** [comment]
do you have flac installed and in your $PATH?

**Comment by benhei** [comment]
No I hadn't,

after installing it, i see some output-lines from flac, but it still results in the same error.
I will be able to provide more detailled information in a few hours, when i get back to the pc that i used to try it.

curb, ffmpeg, flac is all i need to make it run - right?

btw: i'm on a windows machine

**Comment by taf2** [comment]
@benhei, i haven't tried it on windows yet, but I do know it may be a bit picky about the input audio format... I haven't had time to do more with this project... might in the near future
